"""Problem 29: Distinct powers

Consider all integer combinations of  ab
  for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2**2=4, 2**3=8, 2**4=16, 2**5=32
3**2=9, 3**3=27, 3**4=81, 3**5=243
4**2=16, 4**3=64, 4**4=256, 4**5=1024
5**2=25, 5**3=125, 5**4=625, 5**5=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by ab
  for 2 ≤ a ≤ n and 2 ≤ b ≤ n?
"""

from itertools import product

def distinctPowers(limit: int) -> int:
    """Calculate the number of distinct terms that are generate by all combinations of x**y
    where x and y can be any integer between 2 and the limit provided.

    Args:
        limit (int): Maximum mumber to use in combinations
    
    Returns:
        int: Number of distint combinations
    """
    # All possible combintations of a and b
    all_combinations = product(range(2, limit + 1), range(2, limit + 1))

    # All distinct powers
    all_powers = {a**b for a, b in all_combinations}

    # Return the number of distint powers
    return len(all_powers)
